import turtle

size = 20
fred = turtle.Turtle()
fred.penup()

# handle & hilt outline
fred.color('black', 'black')
fred.shape('square')
fred.setpos(0, 0)
fred.stamp()
fred.setpos(1*size, 0*size)
fred.stamp()
fred.setpos(2*size, 0*size)
fred.stamp()
fred.setpos(2*size, 1*size)
fred.stamp()
fred.setpos(3*size, 2*size)
fred.stamp()
fred.setpos(4*size, 3*size)
fred.stamp()
fred.setpos(5*size, 4*size)
fred.stamp()
fred.setpos(6*size, 3*size)
fred.stamp()
fred.setpos(7*size, 3*size)
fred.stamp()
fred.setpos(8*size, 2*size)
fred.stamp()
fred.setpos(9*size, 2*size)
fred.stamp()
fred.setpos(9*size, 3*size)
fred.stamp()
fred.setpos(8*size, 4*size)
fred.stamp()
fred.setpos(7*size, 5*size)
fred.stamp()
fred.setpos(6*size, 5*size)
fred.stamp()
fred.setpos(5*size, 6*size)
fred.stamp()
fred.setpos(5*size, 7*size)
fred.stamp()
fred.setpos(4*size, 8*size)
fred.stamp()
fred.setpos(3*size, 9*size)
fred.stamp()
fred.setpos(2*size, 9*size)
fred.stamp()
fred.setpos(2*size, 8*size)
fred.stamp()
fred.setpos(3*size, 7*size)
fred.stamp()
fred.setpos(3*size, 6*size)
fred.stamp()
fred.setpos(4*size, 5*size)
fred.stamp()
fred.setpos(3*size, 4*size)
fred.stamp()
fred.setpos(2*size, 3*size)
fred.stamp()
fred.setpos(1*size, 2*size)
fred.stamp()
fred.setpos(0*size, 2*size)
fred.stamp()
fred.setpos(0*size, 1*size)
fred.stamp()

# fill hilt
fred.color('black', 'gray')
fred.setpos(1*size, 1*size)
fred.stamp()
fred.setpos(8*size, 3*size)
fred.stamp()
fred.setpos(7*size, 4*size)
fred.stamp()
fred.setpos(6*size, 4*size)
fred.stamp()
fred.setpos(5*size, 5*size)
fred.stamp()
fred.setpos(4*size, 6*size)
fred.stamp()
fred.setpos(4*size, 7*size)
fred.stamp()
fred.setpos(3*size, 8*size)
fred.stamp()

# fill handle
fred.color('black', 'brown')
fred.setpos(4*size, 4*size)
fred.stamp()
fred.setpos(3*size, 3*size)
fred.stamp()
fred.setpos(2*size, 2*size)
fred.stamp()

# outline blade
fred.color('black', 'black')
fred.setpos(8*size, 6*size)
fred.stamp()
fred.setpos(9*size, 7*size)
fred.stamp()
fred.setpos(10*size, 8*size)
fred.stamp()
fred.setpos(11*size, 9*size)
fred.stamp()
fred.setpos(12*size, 10*size)
fred.stamp()
fred.setpos(13*size, 11*size)
fred.stamp()
fred.setpos(14*size, 12*size)
fred.stamp()
fred.setpos(15*size, 13*size)
fred.stamp()
fred.setpos(15*size, 14*size)
fred.stamp()
fred.setpos(15*size, 15*size)
fred.stamp()
fred.setpos(14*size, 15*size)
fred.stamp()
fred.setpos(13*size, 15*size)
fred.stamp()
fred.setpos(12*size, 14*size)
fred.stamp()
fred.setpos(11*size, 13*size)
fred.stamp()
fred.setpos(10*size, 12*size)
fred.stamp()
fred.setpos(9*size, 11*size)
fred.stamp()
fred.setpos(8*size, 10*size)
fred.stamp()
fred.setpos(7*size, 9*size)
fred.stamp()
fred.setpos(6*size, 8*size)
fred.stamp()

# fill blade
fred.color('black', 'gray')
fred.setpos(6*size, 6*size)
fred.stamp()
fred.setpos(7*size, 7*size)
fred.stamp()
fred.setpos(8*size, 8*size)
fred.stamp()
fred.setpos(9*size, 9*size)
fred.stamp()
fred.setpos(10*size, 10*size)
fred.stamp()
fred.setpos(11*size, 11*size)
fred.stamp()
fred.setpos(12*size, 12*size)
fred.stamp()
fred.setpos(13*size, 13*size)
fred.stamp()
fred.setpos(14*size, 14*size)
fred.stamp()

turtle.done()

