import turtle

size = 20
fred = turtle.Turtle()

# handle & hilt outline
fred.shape('turtle')
fred.forward(1.2*size)
fred.left(90)
fred.forward(1.2*size)
fred.right(45)
fred.forward(3*size)
fred.right(90)
fred.forward(3*size)
fred.left(45)
fred.forward(1*size)
fred.left(90)
fred.forward(1*size)
fred.left(45)
fred.forward(3*size)
fred.right(90)
fred.forward(9*size)
fred.left(45)
fred.forward(1*size)
fred.left(90)
fred.forward(1*size)
fred.left(45)
fred.forward(9*size)
fred.right(90)
fred.forward(3*size)
fred.left(45)
fred.forward(1*size)
fred.left(90)
fred.forward(1*size)
fred.left(45)
fred.forward(3*size)
fred.right(90)
fred.forward(3*size)
fred.right(45)
fred.forward(1.2*size)
fred.left(90)
fred.forward(1.2*size)

turtle.done()

